/** Single place where the glyphs used by the interface live. */
export const ICON_GLYPHS = {
  remove: '✕',
  edit: '✎',
  note: '♪',
  sortAsc: '▲',
  sortDesc: '▼',
  warning: '⚠',
  settings: '⚙',
  expand: '▲',
  collapse: '▼',
  close: '✕',
  play: '▶',
  pause: '❙❙',
  stop: '■',
  previous: '❮❮',
  next: '❯❯',
  shuffle: '⤨',
  repeatOne: '↻1',
  list: '☰',
  grid: '▦',
  external: '↗',
  minimize: '─',
  maximize: '▢',
  help: '?',
  back: '←',
  add: '＋',
  search: '⌕',
  more: '⋮',
  verify: '✓',
  check: '✔',
  export: '⤓',
  import: '⤒',
} as const;

export type IconName = keyof typeof ICON_GLYPHS;
